//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrateGoogleSignIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailycolourcollection
    {
        public int id { get; set; }
        public string domainname { get; set; }
        public string tags { get; set; }
        public string search_class { get; set; }
        public Nullable<int> all_visitor { get; set; }
        public Nullable<int> multipage_visitor { get; set; }
        public Nullable<int> transaion_visitor { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
